# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: hcloud-talos-controlplane-gateway
before:
  hooks:
    - go mod tidy
release:
  disable: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
      - "ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/airfocusio/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
docker_manifests:
  - name_template: ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-amd64
  - name_template: ghcr.io/airfocusio/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/airfocusio/{{ .ProjectName }}:latest-amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "0.0.0-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
